Cart/urls.py
from django.urls import path
from . import views

app_name='Cart'

urlpatterns = [
    path('', views.Cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.CartAdd, name='Cart_Add'),
    path('remove/<int:product_id>/', views.CartRemove, name='Cart_Remove'),
]

Order/urls.py
from django.urls import path
from . import views

app_name = 'Order'

urlpatterns = [
    path ('create/', views.Order_Create, name='Create_order'),

]
    


    
        

Shop/urls.py
from xml.dom.minidom import Document
from django.conf import settings
from . import views
from django.urls import path
from django.conf.urls.static import static

app_name='Shop'

urlpatterns =[
    path('', views.product_list,name='Product_List'),
    path('<slug:category_slug>/', views.product_category, name='Product_category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='Product_Detail'),
    
]
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

engine/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('Cart/', include('Cart.urls', namespace='Cart')),
    path('orders/', include('Order.urls', namespace='Order')),
    path('Pay/', include('Payments.urls', namespace='Payments')),
    path('Api/', include('Shop.api.urls',namespace='Api')),
    path('User/', include('Users.urls', namespace='Users')),
    path('', include('Shop.urls', namespace='Shop')),
]

Cart/models.py
from ctypes import addressof
from django.db import models

Cart/forms.py
from django import forms
#added a comment
class CartAddForm(forms.Form):
    quantity = forms.IntegerField( required= True,
                         
                                    label= 'Qty',
                                    widget= forms.NumberInput(
                                        attrs= {'class' : 'form-control',
                                        'name': 'quantity',
                                        'value': '1',
                                        'min' : '1',
                                        'max' : '10',
                                        'step' : '1',
                                        'data-decimals': '0'


                                        }
                                    )

                                    )
   #override = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)
   

Cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from Shop.models import Product
from .cart import Cart
from .forms import CartAddForm
from django.contrib.auth.decorators import login_required
# Create your views here.
@require_POST
def CartAdd(request,product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id= product_id)
    form = CartAddForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity= cd['quantity'])
    return redirect('Cart:cart_detail')


@require_POST

def CartRemove(request,product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('Cart:cart_detail')


@login_required
def Cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddForm(initial={
            'quantity': item['quantity'],
            'override': True

        })
    return render(request,'Cart/cart.html',{'cart':cart})

Cart/templates/Cart/cart.html
{% extends "Shop/base.html" %}
{% load static %}
{% block content %}
<main class="main">
    <div class="page-header text-center" style="background-image: url('assets/images/page-header-bg.jpg')">
        <div class="container">
            <h1 class="page-title">Shopping Cart<span>Shop</span></h1>
        </div><!-- End .container -->
    </div><!-- End .page-header -->
    <nav aria-label="breadcrumb" class="breadcrumb-nav">
        <div class="container">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{% url 'Shop:Product_List' %}">Home</a></li>
                <li class="breadcrumb-item"><a href="#">Shop</a></li>
                <li class="breadcrumb-item active" aria-current="page">Shopping Cart</li>
            </ol>
        </div><!-- End .container -->
    </nav><!-- End .breadcrumb-nav -->

    <div class="page-content">
        <div class="cart">
            <div class="container">
                <div class="row">
                    <div class="col-lg-9">
                        <table class="table table-cart table-mobile">
                            <thead>
                                <tr>
                                    <th>Product</th>
                                    <th>Price</th>
                                    <th>Quantity</th>
                                    <th>Total</th>
                                    <th></th>
                                </tr>
                            </thead>

                            <tbody>
                                {%for item in cart %}
                                {% with product=item.product %}
                                <tr>
                                    <td class="product-col">
                                        <div class="product">
                                            <figure class="product-media">
                                                <a href="{{product.get_absolute_url}}">
                                                    <img src="{{product.image.url}}" alt="Product image">
                                                </a>
                                            </figure>

                                            <h3 class="product-title">
                                                <a href="#">{{product.name}}</a>
                                            </h3><!-- End .product-title -->
                                        </div><!-- End .product -->
                                    </td>
                                    <td class="price-col">${{ item.price }}</td>
                                    <td class="quantity-col">
                                        <div class="cart-product-quantity">
                                            
                                            <input type="number" class="form-control" value="1" min="1" max="10" step="1" data-decimals="0" required>
                                        </div><!-- End .cart-product-quantity -->
                                    </td>
                                    <td class="total-col">${{item.get_total_price}}</td>
                                    <td class="remove-col">
                                        <form action="{% url 'Cart:Cart_Remove' product.id %}" method="POST">
                                            {% csrf_token %}
                                            <button class="btn-remove" type="submit" value="Remove"><i class="icon-close"></i></button>
                                        
                                        </form></td>
                                </tr>
                                {% endwith %}
                                {% endfor %}
                                <!--Tur-->
                                
                            </tbody>
                        </table><!-- End .table table-wishlist -->

                        <div class="cart-bottom">
                            <div class="cart-discount">
                                <form action="#">
                                    <div class="input-group">
                                        <input type="text" class="form-control" required placeholder="coupon code">
                                        <div class="input-group-append">
                                            <button class="btn btn-outline-primary-2" type="submit"><i class="icon-long-arrow-right"></i></button>
                                        </div><!-- .End .input-group-append -->
                                    </div><!-- End .input-group -->
                                </form>
                            </div><!-- End .cart-discount -->

                            <a href="#" class="btn btn-outline-dark-2"><span>UPDATE CART</span><i class="icon-refresh"></i></a>
                        </div><!-- End .cart-bottom -->
                    </div><!-- End .col-lg-9 -->
                    <aside class="col-lg-3">
                        <div class="summary summary-cart">
                            <h3 class="summary-title">Cart Total</h3><!-- End .summary-title -->

                            <table class="table table-summary">
                                <tbody>
                                    <tr class="summary-subtotal">
                                        <td>Subtotal:</td>
                                        <td>${{ cart.get_total_price }}</td>
                                    </tr><!-- End .summary-subtotal -->
                                    <tr class="summary-shipping">
                                        <td>Shipping:</td>
                                        <td>&nbsp;</td>
                                    </tr>

                                    <tr class="summary-shipping-row">
                                        <td>
                                            <div class="custom-control custom-radio">
                                                <input type="radio" id="free-shipping" name="shipping" class="custom-control-input">
                                                <label class="custom-control-label" for="free-shipping">Free Shipping</label>
                                            </div><!-- End .custom-control -->
                                        </td>
                                        <td>$0.00</td>
                                    </tr><!-- End .summary-shipping-row -->

                                    <tr class="summary-shipping-row">
                                        <td>
                                            <div class="custom-control custom-radio">
                                                <input type="radio" id="standart-shipping" name="shipping" class="custom-control-input">
                                                <label class="custom-control-label" for="standart-shipping">Standart:</label>
                                            </div><!-- End .custom-control -->
                                        </td>
                                        <td>$10.00</td>
                                    </tr><!-- End .summary-shipping-row -->

                                    <tr class="summary-shipping-row">
                                        <td>
                                            <div class="custom-control custom-radio">
                                                <input type="radio" id="express-shipping" name="shipping" class="custom-control-input">
                                                <label class="custom-control-label" for="express-shipping">Express:</label>
                                            </div><!-- End .custom-control -->
                                        </td>
                                        <td>$20.00</td>
                                    </tr><!-- End .summary-shipping-row -->

                                    <tr class="summary-shipping-estimate">
                                        <td>Estimate for Your Country<br> <a href="dashboard.html">Change address</a></td>
                                        <td>&nbsp;</td>
                                    </tr><!-- End .summary-shipping-estimate -->

                                    <tr class="summary-total">
                                        <td>Total:</td>
                                        <td>$160.00</td>
                                    </tr><!-- End .summary-total -->
                                </tbody>
                            </table><!-- End .table table-summary -->

                            <a href="{% url 'Order:Create_order'%}" class="btn btn-outline-primary-2 btn-order btn-block">PROCEED TO CHECKOUT</a>
                        </div><!-- End .summary -->

                        <a href="{% url 'Shop:Product_List'%}" class="btn btn-outline-dark-2 btn-block mb-3"><span>CONTINUE SHOPPING</span><i class="icon-refresh"></i></a>
                    </aside><!-- End .col-lg-3 -->
                </div><!-- End .row -->
            </div><!-- End .container -->
        </div><!-- End .cart -->
    </div><!-- End .page-content -->
</main><!-- End .main -->
{% endblock %}
   

Cart/templates/Cart/detail.html
{% extends 'Shop/base.html' %}
{% load static %}
{% block title %}
My Cart
{% endblock%}
{% block body %}
<h1>My Cart</h1>
<table class="cart">
    <thead>
        <tr>
            <th>Image</th>
            <th>Product</th>
            <th>Quantity</th>
            <th>Remove</th>
            <th>Unit price</th>
            <th>Price</th>
        </tr>

    </thead>
    <tbody>
        {%for item in cart %}
        {% with product=item.product %}
        <tr>
            <td>
                <a href="{{product.get_absolute_url}}">
                    <img src="{{product.image.url}}"/>
                </a>
            </td>
            <td>{{product.name}}</td>
            <td>
                <form action="{% url 'Cart:Cart_Add' product.id %}" method="POST">
                    {{item.update_quantity_form.quantity}}
                    {{item.update_quantity_form.override}}
                    <input type="submit" value="Update">
                    {% csrf_token %}

                </form>
                
            </td>
            <td>
                <form action="{% url 'Cart:Cart_Remove' product.id %}" method="POST">
                    <input type="submit" value="Remove">
                    {% csrf_token %}

                </form>
            </td>
            <td class="num">${{ item.price }}</td>
            <td class="num">${{ item.total_price }}</td>
        
        </tr>
        {% endwith %}
        {% endfor %}
        <tr class="total">
            <td>Total</td>
            <td colspan="4"></td>
            <td class="num">${{ cart.get_total_price }}</td>
        </tr>
       
    </tbody>
</table>
<p class="#">
    <a href="{% url 'Shop:Product_List'%}" class="button-light" >Continue Shopping</a>
    <a href="{% url 'Order:Create_order'%}" class="button">Check Out</a>
</p>

{% endblock%}