Cart/urls.py
from django.urls import path
from . import views

app_name='Cart'

urlpatterns = [
    path('', views.Cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.CartAdd, name='Cart_Add'),
    path('remove/<int:product_id>/', views.CartRemove, name='Cart_Remove'),
]

Users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'Users'

urlpatterns = [
    path('register/', views.register, name='Register'),
    path('login/', auth_views.LoginView.as_view(template_name='Users/login.html'), name='Login'),
    
]

engine/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('Cart/', include('Cart.urls', namespace='Cart')),
    path('orders/', include('Order.urls', namespace='Order')),
    path('Pay/', include('Payments.urls', namespace='Payments')),
    path('Api/', include('Shop.api.urls',namespace='Api')),
    path('User/', include('Users.urls', namespace='Users')),
    path('', include('Shop.urls', namespace='Shop')),
]

Users/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image

class Profile(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    image = models.ImageField(default='default.jpg',
                              upload_to='profile_pic/')
                              

    def __str__(self):
        return f'{self.user.username} Profile'

    def save(self,*args,**kwargs):
        super().save()
        img = Image(self.prof_pic.path)
        if img.height > 300 and img.width > 300:
            output_size = (300,300)
            img.thumbnail(output_size)
            img.save(self.prof_pic.path)

        

Users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django import forms
from .models import Profile


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField(
            required=True
            
    )
    def __init__(self, *args, **kwargs) -> None:
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update({'class': 'form-control'})
        self.fields['email'].widget.attrs.update({'class': 'form-control'})
        self.fields['password1'].widget.attrs.update({'class': 'form-control'})
        self.fields['password2'].widget.attrs.update({'class': 'form-control'})

    class Meta:
        model = User
        fields = ['username' ,'email', 'password1', 'password2']

        

class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email']


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image']

Users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import UserRegisterForm, UserUpdateForm, ProfileUpdateForm


def register(request):
    if request.method == 'POST':
       Register_form = UserRegisterForm(request.POST)
       if Register_form.is_valid():
           Register_form.save()
           username = Register_form.cleaned_data.get('username')
           messages.success(request, f'Congratulations!{username},Your account has been created! You are now able to log in')
           return redirect('Users:Login')
    else:
        Register_form = UserRegisterForm()
    return render(request, 'Users/register.html', {'Register_form': Register_form})


@login_required
def profile(request):
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST,
                                   request.FILES,
                                   instance=request.user.profile)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, f'Your account has been updated!')
            return redirect('profile')

    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)

    context = {
        'u_form': u_form,
        'p_form': p_form
    }

    return render(request, 'Users/Profile.html', context)

Users/templates/Users/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>FreeDom - Home of Quality</title>
    <meta name="keywords" content="HTML5 Template">
    <meta name="description" content="FreeDom eCommerce Store">
    <meta name="author" content="p-themes">
    <!-- Favicon -->
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'assets/images/icons/apple-touch-icon.png'%}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'assets/images/icons/favicon-32x32.png'%}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'assets/images/icons/favicon-16x16.png'%}">
    <link rel="manifest" href="{% static 'assets/images/icons/site.html'%}">
    <link rel="mask-icon" href="{% static 'assets/images/icons/safari-pinned-tab.svg'%}" color="#666666">
    <link rel="shortcut icon" href="{% static 'assets/images/icons/favicon.ico'%}">
    <meta name="apple-mobile-web-app-title" content="Molla">
    <meta name="application-name" content="Molla">
    <meta name="msapplication-TileColor" content="#cc9966">
    <meta name="msapplication-config" content="{% static 'assets/images/icons/browserconfig.xml'%}">
    <meta name="theme-color" content="#ffffff">
    <link rel="stylesheet"
        href="{% static 'assets/vendor/line-awesome/line-awesome/line-awesome/css/line-awesome.min.css">
    <!-- Plugins CSS File -->
    <link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css'%}">
    <link rel="stylesheet" href="{% static 'assets/css/plugins/owl-carousel/owl.carousel.css'%}">
    <link rel="stylesheet" href="{% static 'assets/css/plugins/magnific-popup/magnific-popup.css'%}">
    <link rel="stylesheet" href="{% static 'assets/css/plugins/jquery.countdown.css'%}">
    <!-- Main CSS File -->
    <link rel="stylesheet" href="{% static 'assets/css/style.css'%}">
    <link rel="stylesheet" href="{% static 'assets/css/skins/skin-demo-4.css'%}">
    <link rel="stylesheet" href="{% static 'assets/css/demos/demo-4.css'%}">

    <style>
        html,body{
            border:0 ;
            background-color: #f2f4f8;
            overflow: hidden;
            margin: 0;


        }
        .form-group > input{
            width:100%;
            outline-style:none;
            height:30px;
        }
        .flex-link{
            display:flex;
        }
        .flex1 , .flex2{
             margin: 10px;

        }


    </style>
</head>

<body>
    <div class="form-box" style="width:330px;border-radius: 20px;margin-top:16rem;">
        <div class="form-tab">
            <ul class="nav nav-pills nav-fill" role="tablist">
            <li class="nav-item">
                <a class="nav-link active" id="signin-tab" data-toggle="tab" href="#signin" role="tab"
                    aria-controls="signin" aria-selected="true">Login</a>
            </li>
            
        </ul>
        <div class="tab-content" id="tab-content-5">
            <div class="tab-pane fade show active" id="signin" role="tabpanel" aria-labelledby="signin-tab">
                <form action="#" method="post">
                    {% csrf_token %}
                    {% if form.errors %}
                    <p>Your username and password didn't match. Please try again.</p>
                    {% endif %}
                    <div class="form-group" style="padding: 3px;">
                        <label for="singin-email">{{form.username.label_tag}}*</label>
                        {{form.username}}
                        
                    </div><!-- End .form-group -->
                    <div class="form-group" style="padding:3px;">
                        <label for="singin-password">{{form.password.label_tag}}*</label>
                        {{ form.password }}
                    </div><!-- End .form-group -->
                            

                    <div class="form-footer">
                        <button type="submit" class="btn btn-outline-primary-2" style="width:100%;border-radius:22px;">
                            <span>LOG IN</span>
                            <i class="icon-long-arrow-right"></i>
                        </button>

                    </div><!-- End .form-footer -->
                </form>
                <div class="form-choice">
                    <div class="flex-link">
                        <div class="flex1">
                            <a href="#" class="forgot-link">Forgot Your Password?</a>
                        </div>
                        <div class="flex2">
                            <a href="{% url 'Users:Register'%}" class="forgot-link">Register An Account ?</a>
                        </div>
                    </div>
                    
                    <p class="text-center">or sign in with</p>
                    <div class="row">
                        <div class="col-sm-6">
                            <a href="#" class="btn btn-login btn-g">
                                <i class="icon-google"></i>
                                Login With Google
                            </a>
                        </div><!-- End .col-6 -->
                        <div class="col-sm-6">
                            <a href="#" class="btn btn-login btn-f">
                                <i class="icon-facebook-f"></i>
                                Login With Facebook
                            </a>
                        </div><!-- End .col-6 -->
                    </div><!-- End .row -->
                </div><!-- End .form-choice -->
            </div><!-- .End .tab-pane -->
            
        </div><!-- End .tab-content -->
    </div><!-- End .form-tab -->
</div><!-- End .form-box -->
</body>
</html>

Users/templates/Users/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>FreeDom - Home of Quality</title>
    <meta name="keywords" content="HTML5 Template">
    <meta name="description" content="FreeDom eCommerce Store">
    <meta name="author" content="p-themes">
    <!-- Favicon -->
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'assets/images/icons/apple-touch-icon.png'%}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'assets/images/icons/favicon-32x32.png'%}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'assets/images/icons/favicon-16x16.png'%}">
    <link rel="manifest" href="{% static 'assets/images/icons/site.html'%}">
    <link rel="mask-icon" href="{% static 'assets/images/icons/safari-pinned-tab.svg'%}" color="#666666">
    <link rel="shortcut icon" href="{% static 'assets/images/icons/favicon.ico'%}">
    <meta name="apple-mobile-web-app-title" content="Molla">
    <meta name="application-name" content="Molla">
    <meta name="msapplication-TileColor" content="#cc9966">
    <meta name="msapplication-config" content="{% static 'assets/images/icons/browserconfig.xml'%}">
    <meta name="theme-color" content="#ffffff">
    <link rel="stylesheet"
        href="{% static 'assets/vendor/line-awesome/line-awesome/line-awesome/css/line-awesome.min.css">
    <!-- Plugins CSS File -->
    <link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css'%}">
    <link rel="stylesheet" href="{% static 'assets/css/plugins/owl-carousel/owl.carousel.css'%}">
    <link rel="stylesheet" href="{% static 'assets/css/plugins/magnific-popup/magnific-popup.css'%}">
    <link rel="stylesheet" href="{% static 'assets/css/plugins/jquery.countdown.css'%}">
    <!-- Main CSS File -->
    <link rel="stylesheet" href="{% static 'assets/css/style.css'%}">
    <link rel="stylesheet" href="{% static 'assets/css/skins/skin-demo-4.css'%}">
    <link rel="stylesheet" href="{% static 'assets/css/demos/demo-4.css'%}">
    <style>
        html,
        body {
            border: 0;
            background-color: #f2f4f8;
            overflow: hidden;
            margin: 0;
    
    
        }
        .form-group > input{
            width:100%;
            outline-style:none;
            height:30px;
            margin: 0px;
            padding: 0px;
        }
        .flex-link{
            display:flex;
        }
        .flex1 , .flex2{
             margin: 10px;

        }
        label{
            margin: 0px;
            padding: 0;

        }
    </style>
</head>

<body>
    <div class="form-box" style="width:330px;border-radius: 20px;margin-top:16rem;height: 450px;">
        <div class="form-tab">
            <ul class="nav nav-pills nav-fill" role="tablist">
                <li class="nav-item">
                    <a class="nav-link active" id="signin-tab" data-toggle="tab" href="#signin" role="tab"
                        aria-controls="signin" aria-selected="true">Register</a>
                </li>
    
            </ul>
            <div class="tab-content" id="tab-content-5">
                <div class="tab-pane fade show active" id="signin" role="tabpanel" aria-labelledby="signin-tab">
                    <form action="#" method="post">
                        {% csrf_token %}
                        {% for field in Register_form %}
                        <div class="form-group">
                            <label for="singin-email">{{field.label_tag}}*</label>
                            {{field}}
                            
                            
                        </div><!-- End .form-group -->
                        {% endfor%}
    
                        
                        <div class="form-footer">
                            <button type="submit" class="btn btn-outline-primary-2" style="width:100%;border-radius:22px;">
                                <span>Sign Up</span>
                                <i class="icon-long-arrow-right"></i>
                            </button>
                        </div><!-- End .form-footer -->
                    </form>
                    <div class="form-choice">
                        <div class="flex-link">
                            <div class="flex1">
                                <label class="custom-control-label" for="signin-remember">Remember Me</label>
                                <input type="checkbox" class="custom-control-input" id="signin-remember">
                                
                            </div>
                            <div class="flex2">
                                <a href="{% url 'Users:Login'%}" class="forgot-link">Have An Account ?</a>
                            </div>
                        </div>
                        <p class="text-center">or sign in with</p>
                        <div class="row">
                            <div class="col-sm-6">
                                <a href="#" class="btn btn-login btn-g">
                                    <i class="icon-google"></i>
                                    SignUp With Google
                                </a>
                            </div><!-- End .col-6 -->
                            <div class="col-sm-6">
                                <a href="#" class="btn btn-login btn-f">
                                    <i class="icon-facebook-f"></i>
                                    SignUp Facebook
                                </a>
                            </div><!-- End .col-6 -->
                        </div><!-- End .row -->
                    </div><!-- End .form-choice -->
                </div><!-- .End .tab-pane -->
    
            </div><!-- End .tab-content -->
        </div><!-- End .form-tab -->
    </div><!-- End .form-box -->
</body>

</html>